version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8181:8000"
      - "8989:8080"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=raid_clan_manager.settings
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=rsl_clan_manager
      - POSTGRES_USER=rsl_user
      - POSTGRES_PASSWORD=rsl_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rsl_user -d rsl_clan_manager"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: