# Generated by Django 4.2.21 on 2025-05-24 05:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('clan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('clan_boss_level', models.CharField(max_length=50)),
                ('hydra_clash_required_score', models.PositiveIntegerField(default=0)),
                ('chimera_clash_required_score', models.PositiveIntegerField(default=0)),
                ('personal_rewards_cvc_threshold', models.PositiveIntegerField(default=0)),
                ('non_pr_cvc_threshold', models.PositiveIntegerField(default=0)),
                ('clan_level', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField()),
                ('hh_optimiser_link', models.URLField(blank=True, null=True)),
                ('player_power', models.PositiveIntegerField()),
                ('player_id_ingame', models.CharField(max_length=50, unique=True)),
                ('discord_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Siege',
            fields=[
                ('siege_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opponent', models.CharField(max_length=100)),
                ('tier', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
                ('opponent_score', models.PositiveIntegerField()),
                ('outcome_win', models.BooleanField(default=False)),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sieges', to='clans.clan')),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='HydraClash',
            fields=[
                ('hydra_clash_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.PositiveIntegerField()),
                ('clans_scores', models.JSONField(default=dict)),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydra_clashes', to='clans.clan')),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='CvC',
            fields=[
                ('cvc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opponent', models.CharField(max_length=100)),
                ('tier', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
                ('opponent_score', models.PositiveIntegerField()),
                ('personal_rewards_achieved', models.BooleanField(default=False)),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvcs', to='clans.clan')),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.AddField(
            model_name='clan',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='clans', to='clans.player'),
        ),
        migrations.CreateModel(
            name='ChimeraClash',
            fields=[
                ('chimera_clash_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.PositiveIntegerField()),
                ('clans_scores', models.JSONField(default=dict)),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chimera_clashes', to='clans.clan')),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
    ]
