# Generated by Django 4.2.21 on 2025-05-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0002_rename_personal_rewards_achieved_cvc_personal_rewards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='chimera_clash_required_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='hydra_clash_required_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='non_pr_cvc_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='personal_rewards_cvc_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
