# Generated by Django 4.2.21 on 2025-05-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0003_alter_clan_chimera_clash_required_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('banner_lords', 'Banner Lords'), ('high_elves', 'High Elves'), ('sacred_order', 'Sacred Order'), ('barbarians', 'Barbarians'), ('ogryn_tribes', 'Ogryn Tribes'), ('lizardmen', 'Lizardmen'), ('skinwalkers', 'Skinwalkers'), ('orcs', 'Orcs'), ('demonspawn', 'Demonspawn'), ('undead_hordes', 'Undead Hordes'), ('dark_elves', 'Dark Elves'), ('knight_revenant', 'Knight Revenant'), ('dwarves', 'Dwarves'), ('shadowkin', 'Shadowkin'), ('sylvan_watchers', 'Sylvan Watchers'), ('telerian_alliance', 'The Telerian Alliance'), ('gaellen_pact', 'The Gaellen Pact'), ('corrupted', 'The Corrupted'), ('nyresan_union', 'The Nyresan Union')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team_types',
            field=models.ManyToManyField(blank=True, related_name='players', to='clans.teamtype'),
        ),
    ]
