# Generated by Django 4.2.21 on 2025-05-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0004_teamtype_player_team_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
