# Generated by Django 4.2.21 on 2025-05-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0005_alter_player_player_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='chimera_clash_required_score',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Enter score in billions (e.g., 1.5 for 1.5B)', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='hydra_clash_required_score',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Enter score in billions (e.g., 1.5 for 1.5B)', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_power',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Enter player power in millions (e.g., 4.5 for 4.5M)', max_digits=8, null=True),
        ),
    ]
