# Generated by Django 4.2.21 on 2025-05-24 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0007_remove_siege_opponent_remove_siege_opponent_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydraclash',
            name='final_placement',
            field=models.PositiveIntegerField(default=5, help_text='Final position in the clash (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
