# Generated by Django 4.2.21 on 2025-05-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0008_hydraclash_final_placement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text="Player's current level (1-100)"),
        ),
    ]
