# Generated by Django 4.2.21 on 2025-05-25 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0010_alter_clan_clan_boss_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydraRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField()),
                ('score', models.FloatField()),
                ('difficulty', models.CharField(max_length=50)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydra_clashes', to='clans.clan')),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='CvCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField()),
                ('opponent', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('opponent_score', models.IntegerField()),
                ('personal_rewards', models.BooleanField(default=False)),
                ('tier', models.CharField(max_length=50)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvc_records', to='clans.clan')),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
    ]
