# Generated by Django 4.2.21 on 2025-05-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0012_siege_result_alter_chimeraclash_clan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chimeraclash',
            old_name='clans_scores',
            new_name='opponent_scores',
        ),
        migrations.RenameField(
            model_name='hydraclash',
            old_name='clans_scores',
            new_name='opponent_scores',
        ),
        migrations.RemoveField(
            model_name='hydraclash',
            name='final_placement',
        ),
        migrations.AlterField(
            model_name='chimeraclash',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chimera_clashes', to='clans.clan'),
        ),
        migrations.AlterField(
            model_name='hydrarecord',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hydra_history', to='clans.clan'),
        ),
    ]
