# Generated by Django 4.2.21 on 2025-05-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0013_rename_clans_scores_chimeraclash_opponent_scores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chimeraclash',
            name='tier',
        ),
        migrations.RemoveField(
            model_name='hydraclash',
            name='tier',
        ),
    ]
