# Generated by Django 4.2.21 on 2025-05-26 02:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0014_remove_chimeraclash_tier_remove_hydraclash_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='non_pr_cvc_threshold',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='personal_rewards_cvc_threshold',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='LABattle',
            fields=[
                ('battle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opponent_name', models.CharField(max_length=100)),
                ('points_change', models.IntegerField(help_text='Points gained (positive) or lost (negative)')),
                ('my_champions', models.JSONField(default=list, help_text='List of champions used by the player')),
                ('opponent_champions', models.JSONField(default=list, help_text='List of champions used by the opponent')),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_points', models.IntegerField(help_text='Total points after this battle')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='la_battles', to='clans.player')),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
    ]
