# Generated by Django 4.2.21 on 2025-05-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0015_alter_clan_non_pr_cvc_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_points',
            field=models.IntegerField(default=0),
        ),
    ]
