# Generated by Django 4.2.21 on 2025-05-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0016_player_current_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='siege',
            name='opponent_clan',
            field=models.CharField(blank=True, help_text='Name of the opponent clan', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siege',
            name='opponent_score',
            field=models.PositiveIntegerField(default=0, help_text='Score of the opponent clan'),
        ),
    ]
