# Generated by Django 4.2.21 on 2025-06-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0018_alter_teamtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtype',
            name='name',
            field=models.CharField(choices=[('banner_lords', 'Banner Lords'), ('high_elves', 'High Elves'), ('sacred_order', 'Sacred Order'), ('barbarians', 'Barbarians'), ('ogryn_tribes', 'Ogryn Tribes'), ('lizardmen', 'Lizardmen'), ('skinwalkers', 'Skinwalkers'), ('orcs', 'Orcs'), ('demonspawn', 'Demonspawn'), ('undead_hordes', 'Undead Hordes'), ('dark_elves', 'Dark Elves'), ('knight_revenant', 'Knight Revenant'), ('dwarves', 'Dwarves'), ('shadowkin', 'Shadowkin'), ('sylvan_watchers', 'Sylvan Watchers'), ('telerian_alliance', 'The Telerian Alliance'), ('gaellen_pact', 'The Gaellen Pact'), ('corrupted', 'The Corrupted'), ('nyresan_union', 'The Nyresan Union'), ('void', 'Void'), ('spirit', 'Spirit'), ('magic', 'Magic'), ('force', 'Force'), ('support', 'Support'), ('attack', 'Attack'), ('defense', 'Defense'), ('hp', 'HP'), ('legendary', 'Legendary'), ('epic', 'Epic'), ('rare', 'Rare')], max_length=50, unique=True),
        ),
    ]
