# Generated by Django 4.2.21 on 2025-06-12 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0019_alter_teamtype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiegePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siege_plans', to='clans.clan')),
            ],
        ),
        migrations.CreateModel(
            name='PostAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_number', models.IntegerField()),
                ('team_choice', models.CharField(choices=[('banner_lords', 'Banner Lords'), ('high_elves', 'High Elves'), ('sacred_order', 'Sacred Order'), ('barbarians', 'Barbarians'), ('ogryn_tribes', 'Ogryn Tribes'), ('lizardmen', 'Lizardmen'), ('skinwalkers', 'Skinwalkers'), ('orcs', 'Orcs'), ('demonspawn', 'Demonspawn'), ('undead_hordes', 'Undead Hordes'), ('dark_elves', 'Dark Elves'), ('knight_revenant', 'Knight Revenant'), ('dwarves', 'Dwarves'), ('shadowkin', 'Shadowkin'), ('sylvan_watchers', 'Sylvan Watchers'), ('telerian_alliance', 'The Telerian Alliance'), ('gaellen_pact', 'The Gaellen Pact'), ('corrupted', 'The Corrupted'), ('nyresan_union', 'The Nyresan Union'), ('void', 'Void'), ('spirit', 'Spirit'), ('magic', 'Magic'), ('force', 'Force'), ('support', 'Support'), ('attack', 'Attack'), ('defense', 'Defense'), ('hp', 'HP'), ('legendary', 'Legendary'), ('epic', 'Epic'), ('rare', 'Rare')], max_length=50)),
                ('assigned_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clans.player')),
                ('siege_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='clans.siegeplan')),
            ],
        ),
    ]
