# Generated by Django 4.2.21 on 2025-06-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0020_siegeplan_postassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team_types',
        ),
        migrations.AddField(
            model_name='player',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_clan', to='clans.clan'),
        ),
        migrations.AlterField(
            model_name='player',
            name='discord_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_power',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter player power in millions (e.g., 4.5 for 4.5M)', max_digits=10, null=True),
        ),
    ]
