# Generated by Django 4.2.21 on 2025-06-12 11:54

from django.db import migrations


def assign_clans_to_players(apps, schema_editor):
    Player = apps.get_model('clans', 'Player')
    Clan = apps.get_model('clans', 'Clan')

    # Example logic: Assign all players to the first clan
    default_clan = Clan.objects.first()
    if default_clan:
        Player.objects.update(clan=default_clan)


def unassign_clans_from_players(apps, schema_editor):
    Player = apps.get_model('clans', 'Player')
    Player.objects.update(clan=None)


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0021_remove_player_team_types_player_clan_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_clans_to_players, unassign_clans_from_players),
    ]
