# Generated by Django 4.2.21 on 2025-06-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0022_auto_20250612_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team_types',
            field=models.ManyToManyField(blank=True, related_name='players', to='clans.teamtype'),
        ),
    ]
