# Generated by Django 4.2.21 on 2025-06-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0023_player_team_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postassignment',
            name='team_choice',
            field=models.CharField(choices=[('banner_lords', 'Banner Lords'), ('high_elves', 'High Elves'), ('sacred_order', 'Sacred Order'), ('barbarians', 'Barbarians'), ('ogryn_tribes', 'Ogryn Tribes'), ('lizardmen', 'Lizardmen'), ('skinwalkers', 'Skinwalkers'), ('orcs', 'Orcs'), ('demonspawn', 'Demonspawn'), ('undead_hordes', 'Undead Hordes'), ('dark_elves', 'Dark Elves'), ('knight_revenant', 'Knights Revenant'), ('dwarves', 'Dwarves'), ('shadowkin', 'Shadowkin'), ('sylvan_watchers', 'Sylvan Watchers'), ('telerian_alliance', 'Telerian League'), ('gaellen_pact', 'Gaellen Pact'), ('corrupted', 'The Corrupted'), ('nyresan_union', 'Nyresan Union'), ('void', 'Void'), ('spirit', 'Spirit'), ('magic', 'Magic'), ('force', 'Force'), ('support', 'Support'), ('attack', 'ATK'), ('defense', 'DEF'), ('hp', 'HP'), ('legendary', 'Legendary Champions'), ('epic', 'Epic Champions'), ('rare', 'Rare Champions'), ('immune_turn_meter_reduction', 'Immunity - TM Reduction'), ('immune_turn_meter_boosting', 'Immunity - TM Boosting'), ('immune_cooldowns_increasing', 'Immunity - Ability Cooldown Increasing'), ('immune_cooldowns_decreasing', 'Immunity - Ability Cooldown Decreasing'), ('immune_sheep', 'Immunity - Sheep'), ('no_revive', "Champions Can't Be Revived")], max_length=50),
        ),
        migrations.AlterField(
            model_name='teamtype',
            name='name',
            field=models.CharField(choices=[('banner_lords', 'Banner Lords'), ('high_elves', 'High Elves'), ('sacred_order', 'Sacred Order'), ('barbarians', 'Barbarians'), ('ogryn_tribes', 'Ogryn Tribes'), ('lizardmen', 'Lizardmen'), ('skinwalkers', 'Skinwalkers'), ('orcs', 'Orcs'), ('demonspawn', 'Demonspawn'), ('undead_hordes', 'Undead Hordes'), ('dark_elves', 'Dark Elves'), ('knight_revenant', 'Knights Revenant'), ('dwarves', 'Dwarves'), ('shadowkin', 'Shadowkin'), ('sylvan_watchers', 'Sylvan Watchers'), ('telerian_alliance', 'Telerian League'), ('gaellen_pact', 'Gaellen Pact'), ('corrupted', 'The Corrupted'), ('nyresan_union', 'Nyresan Union'), ('void', 'Void'), ('spirit', 'Spirit'), ('magic', 'Magic'), ('force', 'Force'), ('support', 'Support'), ('attack', 'ATK'), ('defense', 'DEF'), ('hp', 'HP'), ('legendary', 'Legendary Champions'), ('epic', 'Epic Champions'), ('rare', 'Rare Champions'), ('immune_turn_meter_reduction', 'Immunity - TM Reduction'), ('immune_turn_meter_boosting', 'Immunity - TM Boosting'), ('immune_cooldowns_increasing', 'Immunity - Ability Cooldown Increasing'), ('immune_cooldowns_decreasing', 'Immunity - Ability Cooldown Decreasing'), ('immune_sheep', 'Immunity - Sheep'), ('no_revive', "Champions Can't Be Revived")], max_length=50, unique=True),
        ),
    ]
