# Generated by Django 4.2.21 on 2025-06-13 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0024_alter_postassignment_team_choice_alter_teamtype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champions', models.JSONField(default=list, help_text='List of champion names')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_teams', to='clans.player')),
                ('team_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_teams', to='clans.teamtype')),
            ],
        ),
    ]
