# Generated by Django 4.2.21 on 2025-07-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0025_arenateam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='current_points',
        ),
        migrations.RemoveField(
            model_name='player',
            name='discord_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='level',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_id_ingame',
        ),
        migrations.AddField(
            model_name='player',
            name='activity',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='chimera_clash_score',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Chimera Clash score in billions', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='chimera_difficulty',
            field=models.CharField(blank=True, choices=[('UNM', 'UNM'), ('NM', 'NM'), ('B', 'B'), ('H', 'H')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='chimera_difficulty_multi',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='player',
            name='dependability',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='development_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='hydra_clash_score',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Hydra Clash score in billions (e.g., 4.5 for 4.5B)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='hydra_difficulty',
            field=models.CharField(blank=True, choices=[('NM', 'NM'), ('B', 'B'), ('H', 'H')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='hydra_difficulty_multi',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='player',
            name='siege',
            field=models.CharField(blank=True, choices=[('Competitive', 'Competitive'), ('Strong', 'Strong'), ('Good', 'Good'), ('Limited', 'Limited'), ('Weak', 'Weak')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='clan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_set', to='clans.clan'),
        ),
    ]
