# Generated by Django 4.2.21 on 2025-07-09 05:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0027_alter_player_options_alter_player_clan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClashScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=3, help_text='Score in billions (e.g., 1.5 for 1.5B)', max_digits=7)),
                ('keys_used', models.PositiveIntegerField(help_text='Number of keys used (0 to 3)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the score was recorded')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clash_scores', to='clans.player')),
            ],
            options={
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.DeleteModel(
            name='HydraRecord',
        ),
        migrations.AddField(
            model_name='chimeraclash',
            name='clash_scores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'clash_scores__count__lte': 30}, related_name='chimera_clashes', to='clans.clashscore'),
        ),
        migrations.AddField(
            model_name='hydraclash',
            name='clash_scores',
            field=models.ManyToManyField(blank=True, limit_choices_to={'clash_scores__count__lte': 30}, related_name='hydra_clashes', to='clans.clashscore'),
        ),
    ]
