# Generated by Django 4.2.21 on 2025-07-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0028_clashscore_delete_hydrarecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clashscore',
            name='type',
            field=models.CharField(choices=[('hydra', 'Hydra'), ('chimera', 'Chimera')], default='hydra', help_text='Type of clash score (Hydra or Chimera)', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CvCRecord',
        ),
    ]
