# Generated by Django 4.2.21 on 2025-07-09 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0029_clashscore_type_delete_cvcrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='clashscore',
            name='chimera_activity',
            field=models.ForeignKey(blank=True, help_text='Chimera Clash activity associated with this score', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chimera_clash_scores', to='clans.chimeraclash'),
        ),
        migrations.AddField(
            model_name='clashscore',
            name='hydra_activity',
            field=models.ForeignKey(blank=True, help_text='Hydra Clash activity associated with this score', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hydra_clash_scores', to='clans.hydraclash'),
        ),
    ]
