# Generated by Django 4.2.21 on 2025-07-25 00:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0030_clashscore_chimera_activity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hydra_weight', models.FloatField(default=0.3, help_text='Weight for Hydra average in ranking calculation (0 to 1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('chimera_weight', models.FloatField(default=0.7, help_text='Weight for Chimera average in ranking calculation (0 to 1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
            options={
                'verbose_name': 'General Setting',
                'verbose_name_plural': 'General Settings',
            },
        ),
        migrations.RemoveField(
            model_name='player',
            name='chimera_clash_score',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hydra_clash_score',
        ),
    ]
