# Generated by Django 4.2.21 on 2025-07-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0031_generalsettings_remove_player_chimera_clash_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ranking_points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
