# Generated by Django 4.2.21 on 2025-08-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0032_player_ranking_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='hydraclash',
            name='delebrate_throw',
            field=models.BooleanField(default=False),
        ),
    ]
