# Generated by Django 4.2.21 on 2025-08-20 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0033_hydraclash_delebrate_throw'),
    ]

    operations = [
        migrations.AddField(
            model_name='postassignment',
            name='selected_arena_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_assignments', to='clans.arenateam'),
        ),
    ]
