# Generated by Django 4.2.21 on 2025-08-22 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clans', '0034_postassignment_selected_arena_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_power',
        ),
    ]
